export const UPLOAD_PROPIC_SUCCESS = 'UPLOAD_PROPIC_SUCCESS';
export const UPLOAD_PROPIC_FAIL = 'UPLOAD_PROPIC_FAIL';
export const UPLOAD_RECPIC_SUCCESS = 'UPLOAD_RECPIC_SUCCESS';
export const UPLOAD_RECPIC_FAIL = 'UPLOAD_RECPIC_FAIL';
